### ISSUE TITLE
error on Poisson system with modified diagonal

### ISSUE THREAD

**Issue by dahtah** [JuliaLinearAlgebra/AlgebraicMultigrid.jl#56]
The following gives me an error: 
```
ml = ruge_stuben(poisson(27000)+24.0*I)
```
This results in: 
ERROR: ArgumentError: reducing over an empty collection is not allowed
It occurs for sufficiently large values on the diagonal, I'm guessing something goes wrong in the coarsening.

**Comment by ranjanan** [comment]
Closed by #83
