### ISSUE TITLE
Unqualified overload of Base.length leads to confusing LoadErrors

### ISSUE THREAD

**Issue by jagot** [JuliaLinearAlgebra/AlgebraicMultigrid.jl#59]
Since this package [overloads `Base.length`](https://github.com/JuliaLinearAlgebra/AlgebraicMultigrid.jl/blob/f74307e2cb0fe18bc6566a56a5f6db5f47342c1f/src/multilevel.jl#L63), without specifying `ml::MultiLevel` as the argument type, you get weird `LoadError`s if you have this package loaded and you call `length` on a object which has no method defined. E.g. `length(nothing)` results in
```
ERROR: LoadError: type Nothing has no field levels
```

**Comment by ViralBShah** [comment]
Should be fairly straightforward to rename `length` to something else. Hopefully a quick search and replace.

**Comment by fredrikekre** [comment]
https://github.com/JuliaLinearAlgebra/AlgebraicMultigrid.jl/pull/64
