### ISSUE TITLE
Dependency cleanup

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLinearAlgebra/AlgebraicMultigrid.jl#65]
Do we need `compat` as a dependency any more? It should be possible to drop it.

Also, why do we need such a specific version of IterativeSolvers.jl. Perhaps we want `0.8.3+` or some such thing. Isn't `0.8` sufficient unless versions prior to 0.8.3 are broken?

**Comment by ViralBShah** [comment]
Compat removed in cfee0f00071ceeae6e6d323d04c1d3557ffacad2

**Comment by vlandau** [comment]
0.8.3 specified the range [0.8.3, 0.9.0), right?

**Comment by ViralBShah** [comment]
I am not sure. I can never remember...

**Comment by vlandau** [comment]
Looks like [it does](https://julialang.github.io/Pkg.jl/v1/compatibility/#compat-pre-1.0-1). :+1:
