### ISSUE TITLE
Got unsupported keyword arguments "strength", "max_levels", "max_coarse"

### ISSUE THREAD

**Issue by mancolric** [JuliaLinearAlgebra/AlgebraicMultigrid.jl#75]
Hello,

Sorry if this is not the right place to post questions.

I have recently installed julia 1.5.3 and AlgebraicMultigrid package. I have previously deleted earlier versions of julia (included hidden files), so the installation is clean. When I execute
`ml = AlgebraicMultigrid.smoothed_aggregation(AUU, strength=SymmetricStrength(), max_levels=10, max_coarse=10)`
I get the following error
`ERROR: MethodError: no method matching smoothed_aggregation(::SparseMatrixCSC{Float64,Int64}; strength=SymmetricStrength{Float64}(0.0), max_levels=10, max_coarse=10) Closest candidates are: smoothed_aggregation(::TA) where {T, V, TA<:SparseMatrixCSC{T,V}} at /home/jcarpio/.julia/packages/AlgebraicMultigrid/RU7pA/src/aggregation.jl:1 got unsupported keyword arguments "strength", "max_levels", "max_coarse" smoothed_aggregation(::TA, ::Type{Val{bs}}) where {T, V, bs, TA<:SparseMatrixCSC{T,V}} at /home/jcarpio/.julia/packages/AlgebraicMultigrid/RU7pA/src/aggregation.jl:1 got unsupported keyword arguments "strength", "max_levels", "max_coarse" smoothed_aggregation(::TA, ::Type{Val{bs}}, ::Any) where {T, V, bs, TA<:SparseMatrixCSC{T,V}} at /home/jcarpio/.julia/packages/AlgebraicMultigrid/RU7pA/src/aggregation.jl:1 got unsupported keyword arguments "strength", "max_levels", "max_coarse"`

Strangely, the code works perfectly in other machines with julia 1.5.3 (but which also have some earlier versions installed), but not in a AMD EPYC 7601 32-Core Processor.

Am I doing something wrong?

**Comment by ViralBShah** [comment]
I believe https://github.com/JuliaLinearAlgebra/AlgebraicMultigrid.jl/pull/58 should fix this.
