### ISSUE TITLE
Move from Travis to Github Actions

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLinearAlgebra/AlgebraicMultigrid.jl#82]
@ranjanan Can we upgrade this package to use the usual tooling like Circuitscape.jl and other packages?

**Comment by ranjanan** [comment]
Yes

**Comment by ViralBShah** [comment]
I already did this...

**Comment by ranjanan** [comment]
@ViralBShah yes you did. Thank you. I did a little more clean up and tagged a new release.
