### ISSUE TITLE
Printed Grid Complexity is wrong (just copies Operator Complexity)

### ISSUE THREAD

**Issue by learning-chip** [JuliaLinearAlgebra/AlgebraicMultigrid.jl#86]
The line `ground = round(op, digits = 3)` below should be `ground = round(g, digits = 3)` instead:

https://github.com/JuliaLinearAlgebra/AlgebraicMultigrid.jl/blob/b40945a7c5c724f65b92b1a2611ca264df483101/src/multilevel.jl#L66-L67

https://github.com/JuliaLinearAlgebra/AlgebraicMultigrid.jl/blob/b40945a7c5c724f65b92b1a2611ca264df483101/src/multilevel.jl#L83-L90

## Package version

AlgebraicMultigrid@0.4.2

**Comment by ranjanan** [comment]
Thank you!

**Comment by ranjanan** [comment]
Fixed by #88
